MyBlogApp/urls.py
from django.urls import path
from django.contrib import admin
from .views import (
    SearchCarView,
    PostListView,
    PostListCarView,
    PostListTechView,
    PostCreateCarView,
    PostCreateTechView,
    UserPostListCarView,
    UserPostListTechView,
    AddCommentCarView,
    AddCommentTechView,
    PostDetailTechView,
    PostDetailCarView,
    LikeCarView,
    LikeTechView,
    UnLikeCarView,
    UnLikeTechView,
    PostUpdateCarView,
    PostDeleteCarView,
    PostUpdateTechView,
    PostDeleteTechView,

)

app_name = 'MyBlogApp'

urlpatterns = [
    path('', PostListView.as_view(), name='MyBlogApp-welcome'),
    path('cars/', PostListCarView.as_view(), name='cars'),
    path('tech/', PostListTechView.as_view(), name='tech'),
    path('cars/carpost/<int:pk>/', PostDetailCarView.as_view(), name='carpost-postcars_detail'),
    path('tech/techpost/<int:pk>/', PostDetailTechView.as_view(), name='techpost-posttech_detail'),
    path('cars/usercars/<str:username>', UserPostListCarView.as_view(), name='usercars-postscars'),
    path('tech/usertech/<str:username>', UserPostListTechView.as_view(), name='usertech-poststech'),
    path('tech/techpost/new/', PostCreateTechView.as_view(), name='techpost-techcreate'),
    path('cars/carpost/new/', PostCreateCarView.as_view(), name='carpost-createcars'),
    path('cars/post/<int:pk>/update/', PostUpdateCarView.as_view(), name='carpost-updatecars'),
    path('cars/post/<int:pk>/delete/', PostDeleteCarView.as_view(), name='carpost-deletecars'),
    path('tech/post/<int:pk>/update/', PostUpdateTechView.as_view(), name='techpost-updatetech'),
    path('tech/post/<int:pk>/delete/', PostDeleteTechView.as_view(), name='techpost-deletetech'),
    path('cars/likecars/<int:pk>', LikeCarView, name='likecars_postcars'),
    path('tech/liketech/<int:pk>', LikeTechView, name='liketech_posttech'),
    path('cars/unlikecars/<int:pk>', UnLikeCarView, name='unlikecars_postcars'),
    path('tech/unliketech/<int:pk>', UnLikeTechView, name='unliketech_posttech'),
    path('cars/add_commentCars/<int:pk>/commentCars/', AddCommentCarView.as_view(), name='add_commentCars'),
    path('tech/add_commentTech/<int:pk>/commentTech/', AddCommentTechView.as_view(), name='add_commentTech'),
    path('searchcar/', SearchCarView.as_view(), name='searchcar'),
]

ZubyTex/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from news import views as news_views



urlpatterns = [
    path('', include('MyBlogApp.urls', namespace='MyBlogApp')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('news/',  news_views.news, name='news'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,   document_root=settings.MEDIA_ROOT)

MyBlogApp/forms.py
from django import forms
from .models import CommentCarPosts, CommentTechPosts, PostCars



class CommentFormCars(forms.ModelForm):
    class Meta:
        model = CommentCarPosts
        fields = ('name','content')

        widgets = {
              'name': forms.TextInput(attrs={'class': 'form-control'}),
              'content': forms.Textarea(attrs={'class': 'form-control'}),
        }

class CommentFormTech(forms.ModelForm):
    class Meta:
        model = CommentTechPosts
        fields = ('name','content')

        widgets = {
              'name': forms.TextInput(attrs={'class': 'form-control'}),
              'content': forms.Textarea(attrs={'class': 'form-control'}),
        }

MyBlogApp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import PostWelcome, PostCars, CommentCarPosts, PostTech, CommentTechPosts
from .forms import CommentFormCars, CommentFormTech
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, HttpResponse
from users.models import Profile
from django.db.models import Q



class SearchCarView(View):
    def get(self, request, *args, **kwargs):
        querysetc = PostCars.objects.all()
        queryc = request.GET.get('qsc')
        if queryc:
            querysetc = querysetc.filter(
                Q(topic__icontains=queryc) |
                Q(name__icontains=queryc)
            ).distinct()
        context = {
            'querysetc': querysetc
        }
        return render(request, 'MyBlogApp:MyBlogApp/CarSearch_results.html', context)


def LikeCarView(request, pk):
    postcars = get_object_or_404(PostCars, id=request.POST.get('postcars_id'))
    likedcars = False
    if postcars.likescars.filter(id=request.user.id).exists():
       postcars.likescars.remove(request.user)
       likedcars = False
    else:
       postcars.likescars.add(request.user)
       likedcars = True
    return HttpResponseRedirect(reverse('MyBlogApp:carpost-postcars_detail', args=[str(pk)]))



def LikeTechView(request, pk):
    posttech = get_object_or_404(PostTech, id=request.POST.get('posttech_id'))
    likedtech = False
    if posttech.likestech.filter(id=request.user.id).exists():
       posttech.likestech.remove(request.user)
       likedtech = False
    else:
       posttech.likestech.add(request.user)
       likedtech = True
    return HttpResponseRedirect(reverse('MyBlogApp:techpost-posttech_detail', args=[str(pk)]))



def UnLikeCarView(request, pk):
    postcars = get_object_or_404(PostCars, id=request.POST.get('postcars_id'))
    unlikedcars = False
    if postcars.unlikescars.filter(id=request.user.id).exists():
       postcars.unlikescars.remove(request.user)
       unlikedcars = False
    else:
       postcars.unlikescars.add(request.user)
       unlikedcars = True
    return HttpResponseRedirect(reverse('MyBlogApp:carpost-postcars_detail', args=[str(pk)]))



def UnLikeTechView(request, pk):
    posttech = get_object_or_404(PostTech, id=request.POST.get('posttech_id'))
    unlikedtech = False
    if posttech.unlikestech.filter(id=request.user.id).exists():
       posttech.unlikestech.remove(request.user)
       unlikedtech = False
    else:
       posttech.unlikestech.add(request.user)
       unlikedtech = True
    return HttpResponseRedirect(reverse('MyBlogApp:techpost-posttech_detail', args=[str(pk)]))




class PostListView(ListView):
    model = PostWelcome
    template_name = 'MyBlogApp/welcome.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5


class PostListCarView(ListView):
    model = PostCars
    template_name = 'MyBlogApp/cars.html'
    context_object_name = 'postscars'
    ordering = ['?']
    paginate_by = 5



class PostListTechView(ListView):
    model = PostTech
    template_name = 'MyBlogApp/tech.html'
    context_object_name = 'poststech'
    ordering = ['-date']
    paginate_by = 2



class UserPostListCarView(ListView):
    model = PostCars
    template_name = 'MyBlogApp/user_postscars.html'
    context_object_name = 'postscars'
    ordering = ['-date']
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return PostCars.objects.filter(by=user).order_by('-date')


class UserPostListTechView(ListView):
    model = PostTech
    template_name = 'MyBlogApp/user_poststech.html'
    context_object_name = 'poststech'
    ordering = ['-date']
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return PostTech.objects.filter(author=user).order_by('-date')



class PostDetailCarView(DetailView):
        model = PostCars

        def get_context_data(self, *args, **kwargs):
            context = super(PostDetailCarView, self).get_context_data(*args, **kwargs)

            stuff = get_object_or_404(PostCars, id=self.kwargs['pk'])
            stuffer = get_object_or_404(PostCars, id=self.kwargs['pk'])
            total_likescars = stuff.total_likescars()
            total_unlikescars = stuffer.total_unlikescars()

            likedcars =False
            unlikedcars = False
            if stuff.likescars.filter(id=self.request.user.id).exists() and stuffer.unlikescars.filter(id=self.request.user.id).exists():
                likedcars = True
                unlikedcars = True
            context['total_likescars'] = total_likescars
            context['total_unlikescars'] = total_unlikescars
            context['likedcars'] = likedcars
            context['unlikedcars'] = unlikedcars
            return context




class PostDetailTechView(DetailView):
        model = PostTech

        def get_context_data(self, *args, **kwargs):
            context = super(PostDetailTechView, self).get_context_data(*args, **kwargs)
            stuff = get_object_or_404(PostTech, id=self.kwargs['pk'])
            stuffer = get_object_or_404(PostTech, id=self.kwargs['pk'])
            total_likestech = stuff.total_likestech()
            total_unlikestech = stuffer.total_unlikestech()

            likedtech =False
            unlikedtech = False
            if stuff.likestech.filter(id=self.request.user.id).exists() and stuffer.unlikestech.filter(id=self.request.user.id).exists():
                likedtech = True
                unlikedtech = True
            context['total_likestech'] = total_likestech
            context['total_unlikestech'] = total_unlikestech
            context['likedtech'] = likedtech
            context['unlikedtech'] = unlikedtech
            return context



class AddCommentCarView(CreateView):
        model = CommentCarPosts
        form_class = CommentFormCars
        template_name = 'MyBlogApp/add_commentCars.html'
        ordering = ['-timestampCars']

        def get_success_url(self):
            return reverse('MyBlogApp:carpost-postcars_detail', kwargs={'pk': self.object.postcars.pk})

        def form_valid(self, form):
            form.instance.postcars_id = self.kwargs['pk']
            return super().form_valid(form)


class AddCommentTechView(CreateView):
    model = CommentTechPosts
    form_class = CommentFormTech
    template_name = 'MyBlogApp/add_commentTech.html'
    ordering = ['-timestampTech']

    def get_success_url(self):
        return reverse('MyBlogApp:techpost-posttech_detail', kwargs={'pk': self.object.posttech.pk})

    def form_valid(self, form):
        form.instance.posttech_id = self.kwargs['pk']
        return super().form_valid(form)


class PostCreateCarView(LoginRequiredMixin, CreateView):
    model = PostCars
    fields = ['topic', 'content', 'imge']

    def form_valid(self, form):
        form.instance.by = self.request.user
        return super().form_valid(form)


class PostCreateTechView(LoginRequiredMixin, CreateView):
    model = PostTech
    fields = ['title', 'content', 'img']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)



class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
        model = PostWelcome
        success_url = '/'

        def test_func(self):
            post = self.get_object()
            if self.request.user == post.author:
                return True
            return False


class PostUpdateCarView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = PostCars
    fields = ['topic', 'content']

    def form_valid(self, form):
        form.instance.by = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.by:
            return True
        return False


class PostDeleteCarView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
        model = PostCars
        success_url = '/'

        def test_func(self):
            post = self.get_object()
            if self.request.user == post.by:
                return True
            return False


class PostUpdateTechView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = PostTech
    fields = ['title', 'author']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteTechView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = PostTech
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

MyBlogApp/templates/MyBlogApp/add_commentCars.html
{% extends "MyBlogApp/base.html"%}
{% load crispy_forms_tags %}
{% block content %}


        <h1>Add New Comment</h1></br></br>
        <div class="form-group">
        <form method = "POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy}}
            <button class="btn btn-outline-info" type="submit">Post</button>
       </form>
        </div>
{% endblock content %}

MyBlogApp/templates/MyBlogApp/baseTech.html
<!DOCTYPE html>
{% load static %}


  <head>
      <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
          <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
          <meta name="HandheldFriendly" content="true">

      <header class="header">
          <!-- Main Navbar-->
      <nav class="navbar navbar-expand-lg">
        <div class="search-area">
          <div class="search-area-inner d-flex align-items-center justify-content-center">
            <div class="close-btn"><i class="icon-"></i></div>
            <div class="row d-flex justify-content-center">
              <div class="col-md-8">

              </div>
            </div>
          </div>
        </div> <h1 class="sidebar-heading"style="color:#DCDCDC">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
              &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<b>Kizi Tech</b></h1>
            <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
          </div>


          <!-- Navbar Menu -->
          {% if user.is_authenticated%}
          <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
                 <li class="nav-item"><h5><a href="{% url 'MyBlogApp:MyBlogApp-welcome' %}" class="btn btn-success btn-lg"> Home</a></h5>
                 </li>&nbsp&nbsp
                <li class="nav-item"><h5><a href="{% url 'MyBlogApp:techpost-techcreate' %}" class="btn btn-success btn-lg">Create Post</a></h5>
              </li>&nbsp&nbsp
              <li class="nav-item"><h5><a href="{% url 'profile' %}" class="btn btn-success btn-lg">Profile</a></h5>
              </li>&nbsp&nbsp
                 {% else %}
                <div class="collapse navbar-collapse">
                 <ul class="navbar-nav ml-auto">
                <li class="nav-item"><h5><a href="{% url 'login' %}" class="btn btn-success btn-lg">Login</a></h5>
              </li>&nbsp&nbsp
              <li class="nav-item">
             <a href="{% url 'register' %}" class="btn btn-success btn-lg">Register</a>
              </li></ul></div>&nbsp&nbsp
             {% endif %}
             {% if messages %}
            {% for message in messages %}
          <div class="alert alert-{{ message.tags}}">
          {{ message }}
          </div>
         {% endfor %}
          {% endif %}
            </ul>

          </div>

        </div>

      </nav>

        </div>
      </nav>
    </header>
<hr style="width:120%;height:10px;border-width:20;color:gray;background-color:lightgray">

  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontastic.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <link rel="stylesheet" href="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<style>
.dropbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px;
  font-size: 16px;
  border: none;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {background-color: #ddd;}

.dropdown:hover .dropdown-content {display: block;}

.dropdown:hover .dropbtn {background-color: #3e8e41;}
</style>
<style>

.fa {
  font-size: 25px;
  cursor: pointer;
  user-select: none;
  color: black;
}

.fa:hover {
  color: darkblue;
}
  .social-menu ul{
      font-size: 25px;
      color: black;
      background: absolute;
      top:5%
      left:5%
      padding:5;
      margin:5;
      transformation: translate(-50%, -50%);
      display: flex
   }
  .social-menu ul.fa{
     font-size: 30px;
     line-height: 60px;
     transition: .6s:
     color:#000;
  }
  .social-menu ul a{
     position: relative;
     display: block;
     width: 60px:
     height:60px;
     border-radius: 50px
     background-color: #000;
   }

</style>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" crossorigin="anonymous">

    <title>Kizi</title>
  </head>
  <body>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  </div>
</nav>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  </body>
</html>

MyBlogApp/templates/MyBlogApp/popUp.html
{% block content %}
{% load static %}

{% if some_flag %}
    <div id="some_flag" title="Some Flag">
        <p>Some Text Here</p>
    </div>
{% endif %}

{% endblock content %}

MyBlogApp/templates/MyBlogApp/post_confirm_delete.html
{% extends "MyBlogApp/base.html"%}
{% block content %}
    <div class="content-section">
       <form method = "POST">
            {% csrf_token %}
            <fieldset class="form-group">
               <legend class="border-bottom mb-4"></legend>
               <h4>Are you sure you want to delete this Post !!!</h4>
           </fieldset>
           <div class="form-group">
               <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
               <button onclick="document.location='{% url 'MyBlogApp:post-detail' object.id %}'">Cancel</button>
           </div>
        </form>
    </div>

{% endblock %}

MyBlogApp/templates/MyBlogApp/post_form.html
{% extends "MyBlogApp/base.html"%}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">

       <form method = "POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
               <legend class="border-bottom mb-4">Post Your Products here</legend>
                {{ form.media}}
                {{ form|crispy}}
           </fieldset>
           <div class="form-group">
               <button class="btn btn-outline-info" type="submit">Post</button>
           </div>
        </form>
    </div>



{% endblock %}

MyBlogApp/templates/MyBlogApp/postcars_confirm_delete.html
{% extends "MyBlogApp/baseCars.html"%}
{% block content %}
    <div class="content-section">
       <form method = "POST">
            {% csrf_token %}
            <fieldset class="form-group">
               <legend class="border-bottom mb-4"></legend>
               <h4>Are you sure you want to delete this Post !!!</h4>
           </fieldset>
           <div class="form-group">
               <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
               <button onclick="document.location='{% url 'MyBlogApp:carpost-postcars_detail' object.id %}'">Cancel</button>
           </div>
        </form>
    </div>

{% endblock %}

MyBlogApp/templates/MyBlogApp/posttech_confirm_delete.html
{% extends "MyBlogApp/baseTech.html"%}
{% block content %}
    <div class="content-section">
       <form method = "POST">
            {% csrf_token %}
            <fieldset class="form-group">
               <legend class="border-bottom mb-4"></legend>
               <h4>Are you sure you want to delete this Post !!!</h4>
           </fieldset>
           <div class="form-group">
               <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
               <button onclick="document.location='{% url 'MyBlogApp:techpost-posttech_detail' object.id %}'">Cancel</button>
           </div>
        </form>
    </div>

{% endblock %}

MyBlogApp/templates/MyBlogApp/posttech_detail.html
{% extends "MyBlogApp/baseTech.html"%}
{% load crispy_forms_tags %}
{% block content %}

                <h5><a href="{% url 'MyBlogApp:tech' %}" class="btn btn-outline-success">Back To Tech</a></h5>
               <div class="article-metadata">
                   <a class="mr-2" href="{% url 'MyBlogApp:usertech-poststech' object.author.username %}">{{ object.author }}</a>
                   <small class="text-muted">{{ object.date|date:"F d, Y" }}</small>
               </div>
               <h2 class="article-title">{{ object.title }}</h2>


               {% if posttech.img %}
               <img src=" {{ posttech.img.url }}" alt="{{ posttech.title }}">
               {% endif %}
               <h2 class="article-content">{{ object.content | safe }}</h2>

       {% if object.author == user %}
                      <div>
                        <button onclick="document.location='{% url 'MyBlogApp:techpost-updatetech' object.id %}' ">Update</button>
                        <button onclick="document.location='{% url 'MyBlogApp:techpost-deletetech' object.id %}'">Delete</button>
                      </div>
        {% endif %}

<br/><br/>
<div>
<form action="{% url 'MyBlogApp:liketech_posttech' posttech.pk %}" method="POST">
    {% csrf_token %}
   {{post.total_likescars}} Likes <button type="submit" name="posttech_id" value="{{ posttech.id }}" class="btn btn-primary btn-sm">Like</button>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <button type="submit" name="posttech_id" formaction="{% url 'MyBlogApp:unliketech_posttech' posttech.pk %}" value="{{ posttech.id }}" class="btn btn-primary btn-sm">UnLike</button> {{post.total_unlikestech}} unLikes
</form>
</div></br></br></br>
<h2>Comments...</h2>
{% if not posttech.commentsTech.all %}
    No Comments Yet...<a href="{% url 'MyBlogApp:add_commentTech' posttech.pk %}">Add Comment</a>
    Add One</a>
{% else %}
<a href="{% url 'MyBlogApp:add_commentTech' posttech.pk %}">Add Comment</a>
    {% for comment in posttech.commentsTech.all %}
        <strong>
             {{ comment.name }} -
             {{ comment.timestampTech }}
        </strong>
        <br/>
        {{ comment.content }}
      </br></br>
    {% endfor %}
{% endif %}
<a href="{% url 'MyBlogApp:add_commentTech' posttech.pk %}">Add Comment</a>





{% endblock content %}

MyBlogApp/templates/MyBlogApp/user_poststech.html
{% extends "MyBlogApp/base.html"%}
{% block content %}

<h1 class="mb-3">Posts by {{view.kwargs.username}} ({{page_obj.paginator.count}})</h1>
   {% for post in poststech %}
       <article class="media content-section">
           <img class="image-responsive" style="width: auto; height: 30px" src="{{ post.author.profile.image.url}}">
           <div class="media-body">
               <div class="article-metadata">
                   <a class="mr-2" href="{% url 'MyBlogApp:usertech-poststech' post.author.username %}">{{post.author}}</a>
                   <small class="text-muted">{{ post.date_post|date:"F d, Y" }}</small>
               </div>
               <h2><a class="article-title" href="{% url 'MyBlogApp:techpost-posttech_detail' post.id %}">{{ post.title }}</a></h2>
               <h2 class="article-content">{{post.content}}</h2>
           </div>
       </article>
    {% endfor %}


{% if is_paginated %}
     {% if page_obj.has_previous %}
       <a class="btn btn-outline-info mb-4" href="?page=1">First </a>
       <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous </a>
     {% endif %}

     {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
          {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'-3' %}
             <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
     {% endfor %}

      {% if page_obj.has_next %}
       <a class="btn btn-outline-info mb-4" href="?page={{page_obj.next_page_number}}">Next</a>
       <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
     {% endif %}

   {% endif %}


{% endblock content %}